language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: HNg5puIpSOIfmP+SSeav1I256mw0sWTlefTYHcUuqrdE+urmIKwIbXu1TZtwL9+AIlQZnrBCihEx7A4Pot7oP2F8xTTLLRQRW0TdVTugHiJe9KGP0Aa9sdd6NhjvMzHFZxiFY8sWHdZPdHRADJDUlBCDncx2lUNQsw1+wL/A21lvALE/LCs+4sggnbYMFcEXF5lyAKhhg3+hxkqOrSDJwv0LJK6Q42Dj+7Kt0iwtmcQ0hz7TEnZVJsvaUk3MSzRF096v2lEp9qjgeND088idcfjZ2bqDjgi1O2A+iful12NvCRvrihuvBnAUiCZdg0Rx1RQz846ydSYe1i9AbAT6UWkv7fIgeF+FsP7AxPDQHTRM6mbokNbNokGNXSD/IKEnDHeoO9yijP2hv5JgKOVxaZKhMn5U2ugeipoJay5zZovcxXRvSm+T91263Loljgho5pzq/t5FTtTmcLxTHvkFFYS+orN6zz3GL8ckBgGNUnBfi+VdRmxCclyMAWRNIqYeoKDIHsNV8whBcwZ8P1Fq9L2CD/bRNjtS0Ts68lbd3iloyUs4ecYmWcOcmxO+uPvxyT7RVE8xJ2mwb+F+RdrtjMCE8kqZNT01CiAPn3K4MHcRRXhIg+3gSXkQgLTPyPz1wSXumwYXzpAyhxb/GX4qVvxB7ECQaJ63MmYBuSKH2gQ=
script:
- pytest
after_success:
  coveralls